---
# Title: Zabbix proxy install Ubuntu
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: tasks/ubuntu/zabbix-proxy-install-docker.yml
#
# Description:
#   Taskfile for deploying Zabbix proxy on Ubuntu
#   via docker.
#
# Source(s):
#   - https://hub.docker.com/r/zabbix/zabbix-proxy-mysql
#   - https://www.zabbix.com/documentation/7.0/en/manual/installation/containers
#
- name: ""
