---
# Title: Zabbix proxy install Ubuntu
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: tasks/ubuntu/zabbix-proxy-install-docker.yml
#
# Description:
#   Taskfile for deploying Zabbix proxy on Ubuntu
#   via docker.
#
# Source(s):
#   - https://hub.docker.com/r/zabbix/zabbix-proxy-mysql
#   - https://www.zabbix.com/documentation/7.0/en/manual/installation/containers
#
- name: "Create Ansible directory structure on host '{{ansible_hostname }}'"
  ansible.builtin.file:
    path: "{{ ansible_dir.path }}"
    owner: "{{ ansible_dir.owner }}"
    group: "{{ ansible_dir.group }}"
    mode: '{{ansible_dire.mode }}'
    state: directory
  loop:
    - { path: '/opt/ansible/', owner: 'root', group: 'root', mode: '0600', desc: 'Ansible directory structure' }
    - { path: '/opt/ansible/docker', owner: 'root', group: 'root', mode: '0600', desc: 'Docker directory structure' }
    - { path: '/opt/ansible/docker/zabbix-proxy/', owner: 'root', group: 'root', mode: '0600', desc: 'Zabbix docker directory structure for compose file' }    
  loop_control:
    loop_var: ansible_dir

- name: "Transfer docker-compose file for Zabbix proxy to directory '/opt/ansible/docker/zabbix-proxy/' on host '{{ ansible_hostname }}'"
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: /opt/ansible/docker/zabbix-proxy/docker-compose.yml
    owner: root
    group: root
    mode: '0600'
    
- name: "Start zabbix-proxy via docker-compose file in directory '/opt/ansible/docker/zabbix-proxy/' on host '{{ ansible_hostname }}'"
  docker_compose:
    project_src: /opt/ansible/docker/zabbix-proxy/
    build: no
