---
# Title: Zabbix proxy install Ubuntu
#
# Author: bitfinity-nl
# Owner: bitfinity-nl
#
# File: tasks/handlers/main.yml
#
# Description:
#   Taskfile for deploying Zabbix proxy on Ubuntu.
#
- name: "import zabbix-dbschema"
  ansible.builtin.raw: "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -u {{ zbx_mariadb_root }} -p{{ zbx_mariadb_root_pwd }} {{ zbx_mariadb_dbname }}"

- name: "reboot_server"
  ansible.builtin.reboot:
  
- name: "enable_start_zabbix-proxy"
  ansible.builtin.systemd:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
    masked: no
  loop:
    - zabbix-proxy
  loop_control:
    loop_var:
     - systemd_service
  

- name: "disable_global_log_bin_trust_function_creators"
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 1
    login_user: "{{ zabbix_proxy_administrative_user }}"
    login_password: "{{ zabbix_proxy_administrative_pass }}"
  no_log: True

- name: "import_database_schema"
  raw: docker exec -it mariadb bash -c 'cat /zabbix_proxy.sql | mariadb --default-character-set=utf8mb4 -uroot -p{{ zabbix_proxy_administrative_pass }} zabbix_proxy'
  no_log: false

- name: "enable_global_log_bin_trust_function_creators"
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 0
    login_user: "{{ zabbix_proxy_administrative_user }}"
    login_password: "{{ zabbix_proxy_administrative_pass }}"
  no_log: True
